name: Build and Deploy Dashboard

on:
  push:
    branches:
      - main
      - dashboard-src

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Install and Build 馃挍
        run: |
          # 修正：直接在根目录运行，不再 cd dashboard
          npm install
          npm run build

      - name: Deploy 馃殕
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # Vite 构建出的文件夹
          branch: gh-pages
